---
- name: Setup Kubernetes Worker Node
  hosts: all
  become: yes
  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes

    - name: Set hostname
      hostname:
        name: kworker-node

    - name: Turn off swap
      shell: swapoff -a

    - name: Comment out swap entry in fstab
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl settings for Kubernetes
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/kubernetes.conf
        state: present
        reload: yes
      loop:
        - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
        - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
        - { name: "net.ipv4.ip_forward", value: "1" }

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Run shell script to add Docker repository
      shell: |
        echo -e "\n" | sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Update apt package index
      shell: sudo apt update -y

    - name: Install containerd.io
      shell: sudo apt install -y containerd.io

    - name: Create directory for containerd configuration
      shell: sudo mkdir -p /etc/containerd

    - name: Configure containerd and save to config file
      shell: sudo containerd config default | sudo tee /etc/containerd/config.toml

    - name: Update containerd config
      shell: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      
    - name: Restart Containerd service
      shell: service containerd restart 

    - name: Update package repositories
      apt:
        update_cache: yes

    - name: Install necessary packages for Kubernetes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

    - name: Download Kubernetes GPG key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update package repositories
      apt:
        update_cache: yes

    - name: Install Kubernetes components
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started

    - name: Copy file.txt to the root user's home directory
      copy:
        src: file.txt  
        dest: "/root/file.txt" 
        owner: root  
        group: root  
        mode: "0644"
      
    - name: Execute command from file.txt
      shell: "bash /root/file.txt"
